import { useState, useEffect, useCallback } from 'react'
import { exchangesApi, pointsApi, optionsAPI } from '@/api'
import type { Exchange, MonthSummary, ExchangeItemRule } from '@shared/types'
import { formatErrorMessage, isAdmin } from '@/utils'
import { useSnackbar } from '@/components/Snackbar'
import Modal from '@/components/Modal'
import ExchangesStatsCards from '@/pages/layout/ExchangesStatsCards'
import ExchangesListTable from '@/pages/layout/ExchangesListTable'
import ExchangesModalAdd from '@/pages/layout/ExchangesModalAdd'
import Loading from '@/components/Loading'
import { parseExchangeData } from '@/pages/layout/OptionsRulesExchange'
export default function Exchanges() {    const { showSnackbar } = useSnackbar()    const [exchanges, setExchanges] = useState<Exchange[]>([])    const [summary, setSummary] = useState<MonthSummary | null>(null)    const [exchangeRules, setExchangeRules] = useState<ExchangeItemRule[]>([])    const [loading, setLoading] = useState(true)    const [showCreate, setShowCreate] = useState(false)    const [revokeId, setRevokeId] = useState<number | null>(null)    const loadData = useCallback(async () => {        try {            const [exchangesData, summaryData, exchangeRulesData] =                await Promise.all([                    exchangesApi.list(),                    pointsApi.summary(),                    optionsAPI.get('exchange').catch(() => null),                ])            // 只显示活跃的兑换记录（排除已撤销的）            setExchanges(exchangesData.filter((e) => e.status === 'active'))            setSummary(summaryData)            if (exchangeRulesData) {                setExchangeRules(parseExchangeData(exchangeRulesData))            }        } catch (err) {            console.error('Failed to load exchanges:', err)        } finally {            setLoading(false)        }    }, [])    useEffect(() => {        loadData()    }, [loadData])    const availableBalance = summary?.availableBalance ?? 0    const minPrivilege = summary?.minimumPointsForPrivileges ?? 100    const handleCreate = async (itemType: string, pointsCost: number) => {        try {            await exchangesApi.create({                itemType,                pointsCost,            })            setShowCreate(false)            showSnackbar('兑换成功')            loadData()        } catch (err) {            showSnackbar('兑换失败: ' + formatErrorMessage(err), 'error')        }    }
const handleRevoke = (id: number) => {        setRevokeId(id)    }
const confirmRevoke = async () => {        if (revokeId === null) return        try {            await exchangesApi.revoke(revokeId)            showSnackbar('撤销成功')            loadData()        } catch (err) {            showSnackbar('撤销失败: ' + formatErrorMessage(err), 'error')        } finally {            setRevokeId(null)        }    }    if (loading) {        return <Loading />    }    return (        <>            <div className="space-y-6">                <div className="flex items-center justify-between">                    <h2>兑换记录</h2>                    {isAdmin() && (                        <button                            disabled={availableBalance < minPrivilege}                            onClick={() => setShowCreate(true)}                            className="btn btn-primary">                            添加兑换                        </button>                    )}
</div>                <ExchangesStatsCards summary={summary} />                <ExchangesListTable                    exchanges={exchanges}                    exchangeRules={exchangeRules}                    onRevoke={handleRevoke}                />            </div>            <ExchangesModalAdd                open={showCreate}                onCancel={() => setShowCreate(false)}                onConfirm={handleCreate}                exchangeRules={exchangeRules}                availableBalance={availableBalance}            />            <Modal                open={revokeId !== null}                title="撤销兑换"                confirmLabel="撤销"                danger                onConfirm={confirmRevoke}                onCancel={() => setRevokeId(null)}>                <p className="text-sm text-gray-600">                    确定撤销此兑换？积分将退回。                </p>            </Modal>        </>    )}